org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=
unityTemplateVersion=20
unityProjectPath=/home/alanacardoso/Desktop/RA/My project
unity.projectPath=/home/alanacardoso/Desktop/RA/My project
unity.debugSymbolLevel=none
unity.buildToolsVersion=34.0.0
unity.minSdkVersion=30
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.unity.template.ar_mobile
unity.abiFilters=arm64-v8a
unity.versionCode=1
unity.versionName=1.0.0
unity.namespace=com.unity.template.ar_mobile
unity.agpVersion=8.7.2
unity.androidSdkPath=/home/alanacardoso/Unity/Hub/Editor/6000.2.6f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=/home/alanacardoso/Unity/Hub/Editor/6000.2.6f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=/home/alanacardoso/Unity/Hub/Editor/6000.2.6f1/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatabilityVersion=VERSION_17
unity.installInBuildFolder=false
android.useAndroidX=true
android.enableJetifier=true
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never